---
title: "linelistBayes: running in parallel"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{linelistBayes: running in parallel}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(linelistBayes)
library(EPISTORMparallel)
```

load data
```{r}
data("sample_dates")
data("sample_location")
data("sample_cases")

head(sample_dates)
head(sample_cases)
```

creating case-counts
```{r}
caseCounts <- create_caseCounts(date_vec = sample_dates,
                                location_vec = sample_location,
                                cases_vec = sample_cases)

```

Get the first wave only
```{r}
caseCounts <- caseCounts[1:80, ]
```

serial interval
```{r}
sip <- si(14, 4.29, 1.18)
```

Run in parallel, this takes ~6 hours
```{r, eval=F}
out_list_parallel <- run_backnow_parallel(caseCounts,
                        MAX_ITER = as.integer(21000),
                        n_chains = as.integer(100),
                        norm_sigma = 0.2,
                        sip = sip,
                        NB_maxdelay = as.integer(20),
                        NB_size = as.integer(6),
                        printProgress = 1,
                        reportF_missP = 0.6)
```

plot
```{r,echo=FALSE, eval=FALSE}
plot(out_list_parallel, "est")
```

```{r,dpi=100, fig.height=2.75, fig.width=6.75,dev='png'}
data("out_list_parallel")
par(oma = c(0, 0, 0, 0), mar = c(4, 4, 1, 1))
plot(out_list_parallel, "est")
```

Get convergence
```{r}
1 - apply(out_list_parallel$geweke_back, 2, mean)
1 - apply(out_list_parallel$geweke_rt, 2, mean) 
```
